name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_INDEX_NAME: ${{ secrets.INDEX_NAME }}
          envkey_API_KEY_SEARCH: ${{ secrets.API_KEY_SEARCH }}
          file_name: .env

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DOCS_TOKEN }}.
          publish_dir: ./build