name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v1.3
      #   with:
      #     envkey_APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      #     envkey_API_KEY: ${{ secrets.API_KEY }}
      #     envkey_INDEX_NAME: ${{ secrets.INDEX_NAME }}
      #     envkey_API_KEY_SEARCH: ${{ secrets.API_KEY_SEARCH }}
      #     file_name: .env
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          echo APPLICATION_ID=${{ secrets.APPLICATION_ID }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo INDEX_NAME=${{ secrets.INDEX_NAME }} >> .env
          echo API_KEY_SEARCH=${{ secrets.API_KEY_SEARCH }} >> .env
          cat .env
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          INDEX_NAME: ${{ secrets.INDEX_NAME }}
          API_KEY_SEARCH: ${{ secrets.API_KEY_SEARCH }}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: yarn

      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: 'PJZVC50ZFW'
          algolia_api_key: 'afcc898bfecc17633f3c2dfc4c4092f9'
          file: 'config.json'

      - name: Install dependencies
#        run: yarn install --frozen-lockfile
        run: yarn install
      - name: Build website
        run: yarn build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Make CNAME
        uses: 'finnp/create-file-action@master'
        env:
          FILE_NAME: './build/CNAME'
          FILE_DATA: 'docs.welldonestudio.io'
      # - name: Make CNAME
      #   run: |
      #     touch ./build/CNAME
      #     echo docs.welldonestudio.io >> ./build/CNAME
      #     cat ./build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
